version: '3.9'

services:
  notes-db-postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=notes_app
      - POSTGRES_USER=notes_app
      - POSTGRES_DB=db_notes

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: notes-db-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: notes_app
    ports:
      - 5050:80