version: '3.9'

services:
  notes-db-postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=notes_app
      - POSTGRES_USER=notes_app
      - POSTGRES_DB=db_notes

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: notes-db-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: notes_app
    ports:
      - 5050:80

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=elastic
      - ELASTIC_USERNAME=elastic
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: 2097152
        hard: 2097152

volumes:
  elasticsearch-volume:
    driver: local